server:
  port: ${SERVER_PORT:8182}
  max-http-header-size: 16KB

spring:
  application:
    name: profile
  main:
    banner-mode: off
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/pre-order-profile
    driver-class-name: org.postgresql.Driver
    username: profile
    password: profile
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true #HHH-12368
#        temp:
#          use_jdbc_metadata_defaults: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
#  kafka:
#    consumer:
#      group-id: tpd-loggers
#      auto-offset-reset: earliest
#    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8184/eureka/

security:
  oauth2:
    client:
      clientId: ${SECURITY_OAUTH2_CLIENT_ID:profile-service}
      clientSecret: ${SECURITY_OAUTH2_CLIENT_SECRET:secret}
      scope: trusted
      accessTokenUri: http://localhost:8177/oauth/token
      userAuthorizationUri: http://localhost:8177/oauth/token

    resource:
      tokenInfoUri: http://localhost:8177/oauth/check_token
      jwt.keyValue: ${SECURITY_OAUTH2_JWT_KEY:jwt-secret}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}
        decode404: ${FEIGN_DECODE_404:true}

logging:
  level:
    .: DEBUG
    feign: DEBUG
    ru.edu: DEBUG
    org.springframework:
      web.filter.CommonsRequestLoggingFilter: DEBUG
#      security: DEBUG

jwt:
  token:
    secret: jwtAppDemo
    expired: 360000

tpd:
  topic-name: advice-topic
  messages-per-request: 10