server:
  port: ${SERVER_PORT:8100}
  max-http-header-size: 16KB

spring:
  application:
    name: api-gateway
  main:
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_DEFAULT_ZONE:localhost}:8085/eureka/

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}
        decode404: ${FEIGN_DECODE_404:true}

hystrix:
  command:
    booking:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    profile:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

zuul:
  ignored-services: '*'
  sensitiveHeaders: Cookie,Set-Cookie
#  prefix: /api/v1
  routes:
    auth:
      path: /api/v1/auth/**
      service-id: api-gateway-auth
      stripPrefix: false
    auth-sso:
      path: /oauth/**
      service-id: api-gateway-auth
      stripPrefix: false
    booking:
      path: /api/v1/booking/**
      service-id: booking
#      url: http://booking/api/v1/booking
      stripPrefix: false
    profile:
      path: /api/v1/profile/**
      service-id: profile
      stripPrefix: false

logging:
  level:
    .: DEBUG
    feign: DEBUG
    ru.edu: DEBUG
    org.springframework:
      web.filter.CommonsRequestLoggingFilter: DEBUG