apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-dev-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dev
spec:
  selector:
    matchLabels:
      app: db-dev
  template:
    metadata:
      labels:
        app: db-dev
    spec:
      containers:
        - name: db
          image: vveryasov/db:1.0.0
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: db-dev-pvc