apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: vveryasov/discovery:1.0.0
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://discovery:8085/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: discovery
spec:
  selector:
    app: discovery
  ports:
    - port: 8085
      targetPort: 8085
  type: LoadBalancer