apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery
spec:
  serviceName: "discovery"
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: vveryasov/discovery:1.0.0
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
#              value: "http://discovery-0.eureka:8085/eureka"
              value: http://discovery:8085/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery
          imagePullPolicy: Always
# http://eureka-0.eureka:8085/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  clusterIP: None
  ports:
    - port: 8085
      name: discovery
  selector:
    app: discovery

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-lb
  labels:
    app: discovery
spec:
  selector:
    app: discovery
#  clusterIP: None
  ports:
    - port: 80
#      name: discovery
      targetPort: 8085
  type: NodePort