server:
  port: ${SERVER_PORT:8888}
  max-http-header-size: 16KB

spring:
  application:
    name: central-configuration
  main:
    banner-mode: off
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shabbirdwd53/config-server
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/