apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: vveryasov/profile:1.0.0
          ports:
            - containerPort: 8091
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://discovery:8085/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db-dev:5432/pre-order-profile"
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: profile
spec:
  selector:
    app: profile
  ports:
    - port: 80
      targetPort: 8091