server:
  port: ${SERVER_PORT:8085}
  max-http-header-size: 16KB

spring:
  application:
    name: discovery
  main:
    banner-mode: off
eureka:
#  instance:
    #eureka's host
#    hostname: ${SERVER_HOST:localhost}
  client:
    #Do not register yourself with the registration center
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      #External service address
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
